name: Update AUR Package

on:
  release:
    types: [published]
  workflow_dispatch:  # 手动触发

jobs:
  update-aur:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check release type
      id: check
      run: |
        RELEASE_TAG="${{ github.event.release.tag_name }}"
        echo "Current release tag: $RELEASE_TAG"
        
        # 检查是否为纯日期格式 (8位数字)
        if [[ "$RELEASE_TAG" =~ ^[0-9]{8}$ ]]; then
          echo "✅ 纯日期版本，继续更新AUR"
          echo "is_date_release=true" >> $GITHUB_OUTPUT
          echo "release_tag=$RELEASE_TAG" >> $GITHUB_OUTPUT
        else
          echo "❌ 跳过预发布版本: $RELEASE_TAG"
          echo "is_date_release=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Setup SSH
      if: steps.check.outputs.is_date_release == 'true'
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
        
    - name: Update AUR package
      if: steps.check.outputs.is_date_release == 'true'
      run: |
        set -e  # 遇到错误立即退出
        
        # 克隆AUR仓库
        git clone ssh://aur@aur.archlinux.org/zed-loc.git aur-repo
        cd aur-repo
        
        LATEST_TAG="${{ steps.check.outputs.release_tag }}"
        DOWNLOAD_URL="https://github.com/TC999/zed-loc/releases/download/$LATEST_TAG/zed-linux-x86_64.tar.gz"
        
        echo "正在更新到版本: $LATEST_TAG"
        echo "下载URL: $DOWNLOAD_URL"
        
        # 更新PKGBUILD版本信息
        sed -i "s/^pkgver=.*/pkgver=$LATEST_TAG/" PKGBUILD
        sed -i "s/^pkgrel=.*/pkgrel=1/" PKGBUILD
        
        # 计算新的SHA256校验和
        echo "计算校验和..."
        NEW_SHA256=$(curl -L -f "$DOWNLOAD_URL" | sha256sum | cut -d' ' -f1)
        echo "新校验和: $NEW_SHA256"
        sed -i "s/^sha256sums=.*/sha256sums=('$NEW_SHA256')/" PKGBUILD
        
        # 生成更新的.SRCINFO文件
        echo "生成.SRCINFO..."
        makepkg --printsrcinfo > .SRCINFO
        
        # 检查是否有更改需要提交
        if git diff --quiet; then
          echo "没有更改需要提交"
          exit 0
        fi
        
        # 提交更改
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add PKGBUILD .SRCINFO
        git commit -m "Update to $LATEST_TAG"
        git push
        
        echo "✅ AUR包更新完成!"
